### ISSUE TITLE
Error: The "componentType" configuration parameter is required for the "layout_update_xml_group" component.

### ISSUE THREAD

**Issue by rudzitis** [magesuite/brand-management#17]
When clicking on the button "Create New Brand" in a Magento 2.4.6-p2 installation the following error occurs:

The "componentType" configuration parameter is required for the "layout_update_xml_group" component. [] {"url":"/admin_pecten/brands/brand/newbrand/key/40361dc....."
 
main.CRITICAL: Magento\Framework\Exception\LocalizedException: The "componentType" configuration parameter is required for the "layout_update_xml_group" component. in /var/www/html/vendor/magento/framework/View/Element/UiComponentFactory.php:405
Stack trace:
#0 /var/www/html/vendor/magento/framework/View/Element/UiComponentFactory.php(424): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataItem(Array, Array, false)
#1 /var/www/html/vendor/magento/framework/View/Element/UiComponentFactory.php(424): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataItem(Array, Array, false)
#2 /var/www/html/vendor/magento/framework/View/Element/UiComponentFactory.php(334): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataItem(Array, Array, false)
#3 /var/www/html/vendor/magento/framework/View/Element/UiComponentFactory.php(231): Magento\Framework\View\Element\UiComponentFactory->mergeMetadata('brands_edit_for...', Array, false)
#4 /var/www/html/vendor/magento/framework/View/Layout/Generator/UiComponent.php(137): Magento\Framework\View\Element\UiComponentFactory->create('brands_edit_for...', NULL, Array)
#5 /var/www/html/vendor/magento/framework/View/Layout/Generator/UiComponent.php(103): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(Object(Magento\Framework\View\Layout\Data\Structure\Interceptor), 'brands_edit_for...', Array, Object(Magento\Framework\View\Layout\Interceptor))
#6 /var/www/html/vendor/magento/framework/View/Layout/GeneratorPool.php(93): Magento\Framework\View\Layout\Generator\UiComponent->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#7 /var/www/html/vendor/magento/framework/View/Layout.php(365): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#8 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(32): Magento\Framework\View\Layout->generateElements()
#9 /var/www/html/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#10 /var/www/html/vendor/magento/framework/View/Page/Builder.php(65): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#11 /var/www/html/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#12 /var/www/html/vendor/magento/framework/View/Layout.php(271): Magento\Framework\View\Layout\Builder->build()
#13 /var/www/html/vendor/magento/framework/View/Layout.php(896): Magento\Framework\View\Layout->build()
#14 /var/www/html/vendor/magento/module-backend/Model/View/Result/Page.php(26): Magento\Framework\View\Layout->getBlock('menu')
#15 /var/www/html/vendor/creativestyle/magesuite-brand-management/Controller/Adminhtml/Brand/Edit.php(48): Magento\Backend\Model\View\Result\Page->setActiveMenu('MageSuite_Brand...')
#16 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): MageSuite\BrandManagement\Controller\Adminhtml\Brand\Edit->execute()
#17 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): MageSuite\BrandManagement\Controller\Adminhtml\Brand\Edit\Interceptor->___callParent('execute', Array)
#18 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): MageSuite\BrandManagement\Controller\Adminhtml\Brand\Edit\Interceptor->Magento\Framework\Interception\{closure}()
#19 /var/www/html/generated/code/MageSuite/BrandManagement/Controller/Adminhtml/Brand/Edit/Interceptor.php(23): MageSuite\BrandManagement\Controller\Adminhtml\Brand\Edit\Interceptor->___callPlugins('execute', Array, Array)
#20 /var/www/html/vendor/magento/framework/App/Action/Action.php(111): MageSuite\BrandManagement\Controller\Adminhtml\Brand\Edit\Interceptor->execute()
#21 /var/www/html/generated/code/MageSuite/BrandManagement/Controller/Adminhtml/Brand/Edit/Interceptor.php(32): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#22 /var/www/html/vendor/magento/framework/App/FrontController.php(245): MageSuite\BrandManagement\Controller\Adminhtml\Brand\Edit\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#23 /var/www/html/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse(Object(MageSuite\BrandManagement\Controller\Adminhtml\Brand\Edit\Interceptor), Object(Magento\Framework\App\Request\Http))
#24 /var/www/html/vendor/magento/framework/App/FrontController.php(146): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(MageSuite\BrandManagement\Controller\Adminhtml\Brand\Edit\Interceptor))
#25 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#26 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#27 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#28 /var/www/html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#29 /var/www/html/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#30 /var/www/html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#31 /var/www/html/pub/index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))

I could fix the error by removing 'layout_update_xml_group' in the file Model/Brands/DataProvider.php function getMeta:

public function getMeta()
    {
        $meta = parent::getMeta();
        $params = $this->request->getParams();
        $groupsToFields = [
            'brand_details' => [
                'enabled_group' => 'use_config.enabled',
                'brand_name_group' => 'use_config.brand_name',
                'brand_icon_group' => 'use_config.brand_icon',
                'brand_additional_icon_group' => 'use_config.brand_additional_icon',
                'brand_url_key_group' => 'use_config.brand_url_key',
                'is_featured_group' => 'use_config.is_featured',
                **//--> removed 'layout_update_xml_group' => 'use_config.layout_update_xml',**
                'content_constructor_content_group' => 'use_config.content_constructor_content',
                'show_in_brand_carousel_group' => 'use_config.show_in_brand_carousel',
                'short_description_group' => 'use_config.short_description',
                'full_description_group' => 'use_config.full_description',
                'brand_group_identifier_group' => 'use_config.brand_group_identifier'
            ],
            'brand_seo' => [
                'meta_robots_group' => 'use_config.meta_robots',
                'meta_title_group' => 'use_config.meta_title',
                'meta_description_group' => 'use_config.meta_description'
            ]
        ];

**Comment by ggm-dev** [comment]
I get the same error in 2.4.5p4.   Has the fix you mentioned been ok for you?

Thanks - 
David

**Comment by rudzitis** [comment]
So far, yes, but I'm still developing our new shop and have not tested all functions.

**Comment by ggm-dev** [comment]
Thanks - so far so good here as well.  

I'll share a patch in case it helps anyone as the patch on #14 throws an error (at least for me)

```
diff --git a/vendor/creativestyle/magesuite-brand-management/Model/Brands/DataProvider.php b/vendor/creativestyle/magesuite-brand-management/Model/Brands/DataProvider.php
index 4ef805008..d84b3b2a8 100644
--- a/vendor/creativestyle/magesuite-brand-management/Model/Brands/DataProvider.php
+++ b/vendor/creativestyle/magesuite-brand-management/Model/Brands/DataProvider.php
@@ -117,7 +117,6 @@ class DataProvider extends \Magento\Ui\DataProvider\AbstractDataProvider
                 'brand_additional_icon_group' => 'use_config.brand_additional_icon',
                 'brand_url_key_group' => 'use_config.brand_url_key',
                 'is_featured_group' => 'use_config.is_featured',
-                'layout_update_xml_group' => 'use_config.layout_update_xml',
                 'content_constructor_content_group' => 'use_config.content_constructor_content',
                 'show_in_brand_carousel_group' => 'use_config.show_in_brand_carousel',
                 'short_description_group' => 'use_config.short_description',
```
